name: movie_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  accordion: ^2.5.1
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  http: ^0.13.5
  adblocker_webview: ^1.0.0
  flashy_tab_bar2: ^0.0.6
  google_fonts: ^4.0.4
  lottie: ^2.6.0
  webview_flutter: ^4.2.4
  dio: ^5.3.3
  html: ^0.15.4
  lecle_yoyo_player: ^0.0.6
  better_player: ^0.0.83
  fluttertoast: ^8.2.2
  flutter_vlc_player: ^7.4.0
  url_launcher: ^6.1.14
  android_intent_plus: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
